repos:
  - repo: local
    hooks:
      - id: ipynb-cleaner
        name: Notebook Output Cleaner
        description: This hook clears Jupyter Notebook output and metadata
        entry: ./.githooks/ipynb-fmt.sh
        language: script
        types: [file]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
