repos:
  - repo: local
    hooks:
      - id: ipynb-cleaner
        name: Notebook Output Cleaner
        description: This hook clears Jupyter Notebook output and metadata
        entry: ./hooks/ipynb-fmt.sh
        language: script
        types: [file]
