from .coords_mapper_widget import CoordinatesMapper
from .detector_widget import DetectorWidget
from .marker_selector_widget import MarkerSelectorBBoxWidget
from .roi_selector import ROISelectorBBoxWidget
