from .coords_mapper_widget import CoordinatesMapperWidget
from .detector_widget import DetectorWidget, DetectorWidgetCombined
from .marker_selector_widget import MarkerSelectorBBoxWidget
from .roi_selector_widget import ROISelectorBBoxWidget
